[토르] 코틀린 로또 미션 제출합니다
woowacourse-study/2023-Kotlin-Basic pull request #1
Opened 2023-01-08 06:40 UTC by injoon2019

오랜만에 미션하니까 왜 이렇게 어렵죠..?? 리뷰 잘 부탁드립니다

2023-01-10 08:16 UTC, Ohzzi requested changes
반갑습니다 Thor :)
굉장히 빠르게 구현해 주셨군요. 수동과 수익률은 없지만 코틀린을 배우는 것이 목적이므로 완성한 부분까지 리뷰했습니다 :) 남는 것이 시간인 백수인 만큼 최대한 꼼꼼하게 리뷰해보려고 노력했습니다 :) 질문은 댓글이나 카톡으로 해주시면 됩니다!

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +    }
```suggestion
    override fun toString(): String {
        return "$value"
    }
```

이렇게 사용할 수도 있을 것 같아요

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +        }
require 대신 직접 throw 하는 방식을 선택하셨군요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Numbers.kt
> +        }
also 배워갑니다 👍

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Numbers.kt
> +        }
다만 `(1..45)`로 그냥 사용해도 상관없을 것 같아요. 
```suggestion
        private val values = (1..45)
```
`(1..45)`로 사용하게 되면 IntRange 라는 타입으로 나오게 되는데, IntRange도 Iterable의 구현체이기 때문에 shuffled() 메서드가 구현되어 있어서 아래의 getShuffledNumbers에서 그대로 사용할 수 있을 것 같아요.

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Numbers.kt
> +class Numbers {
이 클래스는 정적 변수와 정적 메서드만 제공하고 있네요? 그렇다면 class가 아니라 object로 만드는 것이 어떨까요? 그러면 companion object도 제거할 수 있을 것 같아요!

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/result/Judge.kt
> +        val results = mutableMapOf<Int, Int>(Pair(1, 0), Pair(2, 0), Pair(3, 0), Pair(4, 0), Pair(5, 0))
```suggestion
        val results = mutableMapOf(
            *((1..5).map { Pair(it, 0) }
                .toTypedArray())
        )
```
Stream을 사용하는 방법도 있을 수 있겠네요

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/result/JudgeResult.kt
> +        }
```suggestion
        return when {
            sameCount == 6 -> 1
            sameCount == 5 && bonusWin -> 2
            sameCount == 5 -> 3
            sameCount == 4 -> 4
            else -> 5
        }
```
이렇게 해보는 것은 어떨까요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/InputView.kt
> +    companion object {
코틀린에서는 최상위 함수를 정의할 수 있습니다. (클래스 외부에 함수 정의)
최상위 함수를 사용하면 view에 있는 모든 클래스와 companion object를 제거할 수 있을 것 같아요!

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +class OutputView {
클래스를 제거하고 InputView와 OutputView를 Views.kt라는 하나의 파일로 관리하는 것은 어떨까요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +        fun printResult(lottoResult: MutableMap<Int, Int>) {
MutableMap만 들어온다고 선언할 필요가 있을까요? Mutable할 필요가 없는 부분인 것 같은데, 상위 인터페이스인 Map으로 선언하는게 더 나을 수도 있을 것 같습니다 :)

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/test/kotlin/lotto/domain/Lotto/LottoFactoryTest.kt
> +    @MethodSource("generateUnitConditions")
`@CsvSource`로도 충분하지 않을까요? `@MethodSource`의 가독성에 대해서 한 번 고려해봐도 좋을 것 같아요.

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +            if (numbers.toMutableSet().size != 6) {
매직 넘버는 제거해 봅시다 :)

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +            validateCount(numbers)
count를 검증하는 로직은 어떤 상황에서도 객체 생성마다 보장되어야 하는데, init으로 가는게 좋지 않을까요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +data class Number(
코틀린에도 Number라는 클래스가 있기 때문에 클래스 명이 조금 헷갈릴 수 있을 것 같아요

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        numbers.contains(number)
```suggestion
    private fun contains(number: Number) = numbers.contains(number)
```
inline으로 써도 되지 않을까요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        fun ofNumbers(numbers: MutableList<Number>): Lotto {
인자가 하나이기 때문에 ofNumbers 보다는 fromNumbers가 더 적절하지 않을까요?
그리고 numbers의 타입이 MutableList일 필요가 없지 않을까요? Mutable해야 한다고 강조하는게 아니라면 상위 인터페이스로도 충분할 것 같아요 :)

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        }
```suggestion
        val sameCount = numbers.count { winningLotto.numbers.contains(it) }
        val bonusWin = numbers.contains(bonusNumber)
```
코드를 매우 간결하게 줄일 수 있을 것 같아요 :)

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        fun ofInt(numbers: List<Int>): Lotto {
여기도 마찬가지로 fromInts가 더 적절하지 않을까 싶습니다 :)

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +                .toMutableList())
ofNumbers의 매개변수 타입 선언을 MutableList로 해서 toMutableList를 호출하게 된 것 같네요.
그런데 로또 번호는 한 번 정해지면 변하지 않죠. 오히려 toList를 호출해야 하지 않을까요?
매개변수 타입이 MutableList가 아니라 List면 그렇게 할 수 있을 것 같네요 😄

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/InputView.kt
> +            kotlin.runCatching {
```suggestion
            runCatching {
```
runCatching에 대해 배워갑니다 :) 다만 kotlin은 빼도 될 것 같아요!

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/InputView.kt
> +                return input.toLong()
toLong을 두 번 호출하는것이 뭔가 어색해보이기는 하네요. 조금 더 개선할 방법이 없을까요??

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/InputView.kt
> +                    .map { it.toInt() }
27번 라인에서는 toLong, 30번 라인에서는 toInt로 서로 다른 메서드를 호출하고 있네요 😭

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +            println("---------")
삼중 따옴표를 사용해보는 것은 어떨까요??

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/test/kotlin/lotto/domain/Lotto/NumbersTest.kt
> +    }
1, 6, 45에 대해서 테스트하는 이유가 있을까요?

2023-01-10 08:16 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/LottoFactory.kt
> +    }
만약 1000원 미만, 극단적으로는 음수의 값이 들어오게 되면 어떻게 되나요?

2023-01-10 14:14 UTC, devHudi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +    }
오 이거 신기하네요

2023-01-10 14:15 UTC, devHudi commented on lotto/src/main/kotlin/lotto/domain/result/Judge.kt
> +        val results = mutableMapOf<Int, Int>(Pair(1, 0), Pair(2, 0), Pair(3, 0), Pair(4, 0), Pair(5, 0))
`to` 중위 함수는 `Pair` 를 반환하는데, 이를 사용해보는건 어떨까요?

2023-01-10 15:22 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +    }
오? 요거는 이름이 뭘까요 문자열 템플릿..? 은 아닐거 같은데 무튼 좋네요

2023-01-10 15:25 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +    }
![image](https://user-images.githubusercontent.com/46641538/211591639-23cbdd82-091b-4669-8d33-f2d93f7808eb.png)

저는 이렇게 뜨는데 혹시 코틀린 버전이 다를까요??

2023-01-10 15:25 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +        }
넵! 요거는 require 저도 처음엔 쓰다가 회사에서 쓰는대로 쓰게 되네요 ㅎㅎ

2023-01-10 15:33 UTC, Ohzzi commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +    }
```suggestion
    override fun toString(): String {
        return "$value"
    }
```
ㅎㅎ ㅈㅅ... 이거입니다

2023-01-10 15:40 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Numbers.kt
> +        }
ㄷㄷ 제가 생각하던것보다 훨씬 편하네요 감사합니다!

2023-01-14 05:29 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Numbers.kt
> +class Numbers {
좋네요! ㅎㅎ 아직 object를 정확히 언제 써야할지 모르긴하겠네요. 싱글턴으로 만들어주고 생성자를 객체 선언에서 쓸 수 없다. 요렇게만 인지하고 있고 실무에서는 안써본거 같은데 지금 같은 경우 쓰면 좋을 것 같습니다!

2023-01-14 05:44 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/result/Judge.kt
> +        val results = mutableMapOf<Int, Int>(Pair(1, 0), Pair(2, 0), Pair(3, 0), Pair(4, 0), Pair(5, 0))
좋네요 ㅎㅎ 이거는 안익숙했는데 익숙해지도록 노력해보겠습니다~

2023-01-14 05:46 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/result/JudgeResult.kt
> +        }
크 좋습니다!

2023-01-14 05:48 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/view/InputView.kt
> +    companion object {
좋네요 뭔가 회사에서는 기존 코드들이 자바의 유틸성이면 관습적으로 companion object 안에 정의되어있는데 요렇게 해보는게 좋은거 같습니다

2023-01-14 05:49 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +class OutputView {
클래스 제거는 했고 InputView OutputView 합치는건 좋나 안좋나 뚜렷한 판단이 안서긴하네요(안좋다를 돌려 말한게 아니라 진짜 모르겠음) ㅎㅎ 그래서 일단 스킵

2023-01-14 05:50 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +        fun printResult(lottoResult: MutableMap<Int, Int>) {
코틀린 인액션 읽다보니 이 내용 나오더라고요 감사합니다!

2023-01-14 05:51 UTC, injoon2019 commented on lotto/src/test/kotlin/lotto/domain/Lotto/LottoFactoryTest.kt
> +    @MethodSource("generateUnitConditions")
저도 원래 csv source 를 썼는데 회사 코드에 이렇게 되어있어서 익숙해지려고 연습을 해보고 있어서 적용해봤습니다! 회사에서는 왜 이렇게 썼는지는 한번 봐야겠어요!

2023-01-14 05:55 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +            validateCount(numbers)
오 좋습니다!!

2023-01-14 05:57 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Number.kt
> +data class Number(
요거는 항상 고민이 되네요. A라는 도메인 패키지 하위에 있는데 A를 prefix를 붙일지 말지

2023-01-14 05:58 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        numbers.contains(number)
넵! 요거는 팀 컨벤션이라 익숙해졌는데 개인적 취향이라 봐주십셔!

2023-01-14 05:59 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        fun ofNumbers(numbers: MutableList<Number>): Lotto {
둘다 너무 맞는말입니다!

2023-01-14 06:33 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/view/OutputView.kt
> +            println("---------")
팀 내에서는 삼중 따옴표는 trimIndent()를 사용할때 명시적으로 나타내기 위해 사용하긴 해서요!

2023-01-14 06:33 UTC, injoon2019 commented on lotto/src/test/kotlin/lotto/domain/Lotto/NumbersTest.kt
> +    }
별 이유는 ㅎ

2023-01-14 06:35 UTC, injoon2019 commented
코드 리뷰 너무 좋네요. 평일에 퇴근이 좀 늦어서 주말에 반영했습니다 ㅎㅎ

2023-01-14 06:39 UTC, injoon2019 commented on lotto/src/main/kotlin/lotto/domain/Lotto/Lotto.kt
> +        }
크 이런 내장 함수가 아직 안익숙한데 감사합니다

2023-01-15 13:33 UTC, Ohzzi approved these changes
반영해주신 내용 잘 보았습니다. 역시 현직자라 그런지 훌륭하시네요 ㅎㅎ approve 하겠습니다!

2023-01-16 02:14 UTC, merged