[후디] 코틀린 워들 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #10
Opened 2023-01-24 15:19 UTC by devHudi

하루 컷 해버려서 코드가 난리났네요 ^-^..
PR은 지금 제출하지만 틈틈히 개선 커밋 올리겠습니다 😅

2023-01-28 06:29 UTC, hyewoncc requested changes
안녕하세요, 후디~ 
역시 코틀린을 잘쓰시는군요... 
리팩터링 하실 것 같은 부분은 남겨두고 우선 리뷰 남겨봤습니다 
머지까지 화이팅!!

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +        val todayWord = todayWordPicker.pick(now)
단어를 제출할 때 마다 현재 시각으로 정답을 다시 정하고 있네요
진행 중에 날짜가 넘어간다면 답도 같이 바뀔 것 같아요!

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +    private val submittedWords = mutableMapOf<Word, LetterCompareResults>()
키값 `Word`는 사용하는 곳이 없고, 게임 규칙 상 비교 결과의 순서가 보장되어야 하는데 `Map` 자료구조를 선택하신 이유가 있을까요? 
출력 부분에서도 `List`로 변환하고 있어서 그냥 `List`를 쓰면 어떨까? 생각했습니다

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/Application.kt
> +private fun <T> retry(function: () -> T): T {
👍

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +        val submittedWord = Word(text)
파라미터로 `Word`가 아닌 `String`을 받는 이유가 있을까요?

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +            throw IllegalArgumentException("단어 리스트에 존재하는 단어를 제출해야합니다.")
저는 `require`를 적극적으로 사용하는 편인데요, 안쓰는 이유가 있으신지 궁금합니다😄

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +        val letterCompareResult = submittedWord.compareWithCorrectAnswer(todayWord)
```suggestion
        val letterCompareResults = submittedWord.compareWithCorrectAnswer(todayWord)
```

메서드 반환값이 `LetterCompareResults`인데 왜 `LetterCompareResult`를 반환하고 있지?? 하고 착각해서 살짝...

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Letter.kt
> +    private val position: Int
오 `position` 값을 주는 건 좋은 아이디어네요! 
그런데 위치라는 속성이 `Word`와 독립적으로 `Letter`혼자 가질 수 있는 속성일가? 고민하게 되는 것 같아요

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Letter.kt
> +private const val MAX_POSITION = 6
단어의 위치값이라면 5가 맞지 않을까요?!

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Letter.kt
> +            throw IllegalArgumentException("위치는 반드시 1~6 사이여야 합니다. (입력: ${position})")
위에서 저렇게 생각한 이유는 이 부분이 `Word`과 책임이 섞여있지 않나? 싶어서였습니다 
만약 규칙이 바뀌어서 4글자 단어가 된다면 `Word`와 `Letter` 둘 다 변경이 생기겠네요!

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +    fun compareWithCorrectAnswer(correctAnswer: Word): LetterCompareResults {
현재 로직에 오류가 있는데요,
정답이 `covet`, 답이 `click` 일 때
🟩⬜️⬜️⬜️⬜️ 이 아닌 🟩⬜️⬜️🟨⬜️이 나오고 있습니다
리팩토링 하면서 고쳐보면 어떨까요?

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +        }.toList()
`mapIndexed` 좋은 기능 알아갑니다 ✅ 
별 것 아니지만 `string` 변수명을  `char`로 바꿔주면 어떨까요?

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +        return true
```suggestion
        return letters == other.letters
```
와 차이가 있나요?!

2023-01-28 06:29 UTC, hyewoncc commented on wordle/src/main/kotlin/view/View.kt
> +    println("${currentRound}/6")
```suggestion
    println("$currentRound/6")
```
이렇게도 가능합니다 ~

2023-01-29 10:32 UTC, devHudi commented on wordle/src/main/kotlin/domain/Word.kt
> +        return true
인텔리제이에서 자동 생성된 코드라서 따로 수정하지는 않았습니다!

2023-01-29 10:35 UTC, devHudi commented on wordle/src/main/kotlin/view/View.kt
> +    println("${currentRound}/6")
오호 꿀팁 감사합니다 ㅎㅎ 

코틀린 인 액션 68p에 따르면

> 문자열 템플릿 안에서 변수 이름만 사용하는 경우라도 ${name} 처럼 중괄호로 변수명을 감싸는 습관을 들이면 더 좋다. 필요할 때 정규식등을 통해 검색하거나 일괄 변화할 때도 중괄호를 쓴 경우 처리가 더 쉽고, 코드를 사람이 읽을 때도 문자열 템플릿 안에서 변수가 쓰인 부분을 더 쉽게 식별할 수 있다.

라고 나와있는데요, 이 부분은 어디까지나 주관적인 부분이므로 각자 편한 방식대로 쓰면 좋을 것 같습니다 🙂

2023-01-29 10:38 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +        val todayWord = todayWordPicker.pick(now)
오 그러네요 예리한 리뷰 감사드립니다!
submit 할때가 아니라 game 이 생성되는 시점에 날짜를 설정하도록 변경했습니다!

2023-01-29 11:30 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +    private val submittedWords = mutableMapOf<Word, LetterCompareResults>()
말씀해주신대로 Map 자료구조를 사용할 이유가 없어서 List로 변경하였습니다!

2023-01-29 11:31 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +        val submittedWord = Word(text)
외부에서 호출을 편하게 하기 위해서 (Word로 한번 감싸지 않아도 되므로) 이렇게 작성했습니다!

2023-01-29 11:32 UTC, devHudi commented on wordle/src/main/kotlin/domain/Word.kt
> +        }.toList()
`string` 과 `char` 모두 생각해보니 자료형의 이름이라서, `letter` 를 사용하도록 변경했는데 어떠신가요?

2023-01-29 11:37 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +        val letterCompareResult = submittedWord.compareWithCorrectAnswer(todayWord)
ㅋㅋㅋㅋ ㅠ 코드가 난리났네요

2023-01-29 11:37 UTC, devHudi commented on wordle/src/main/kotlin/domain/Letter.kt
> +private const val MAX_POSITION = 6
맞습니다 .. 하하

2023-01-29 11:41 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +            throw IllegalArgumentException("단어 리스트에 존재하는 단어를 제출해야합니다.")
이 부분에는 require 를 사용해도 무방하나, 던지는 예외가 IAE로 제한되어 사용을 한번 지양해보았습니다!

2023-01-29 11:42 UTC, devHudi commented on wordle/src/main/kotlin/domain/Letter.kt
> +    private val position: Int
저도 만들고 보니 position 을 Letter 가 직접 관리하는게 굉장히 어색하다고 느껴졌어요. Letter 들의 위치를 관리하는 책임은 Word에 있어 보였거든요. 써머 의견대로 시간이 많았다면 Letter가 position 을 갖지 않도록 바꿀 것 같아요 🥲

2023-01-29 11:42 UTC, devHudi commented on wordle/src/main/kotlin/domain/Letter.kt
> +            throw IllegalArgumentException("위치는 반드시 1~6 사이여야 합니다. (입력: ${position})")
100% 동의합니다!..

2023-01-29 14:37 UTC, devHudi commented on wordle/src/main/kotlin/domain/Word.kt
> +    fun compareWithCorrectAnswer(correctAnswer: Word): LetterCompareResults {
로직 수정 + 테스트 케이스 추가 + 리팩토링 세가지 진행했습니다! 코드가 좀 많이 바뀌었네요 😅 더 리팩토링 할 부분이 많긴한데 시간관계상 여기까지만 하고 제출하겠습니다!

2023-02-01 14:00 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +        }.toList()
아주~ 좋습니다👍

2023-02-01 14:02 UTC, hyewoncc commented on wordle/src/main/kotlin/view/View.kt
> +    println("${currentRound}/6")
오 이런 내용이 있군요... 읽어보니 설득되었어요👍 좋은 정보 알려주셔서 감사합니다!!

2023-02-01 14:33 UTC, hyewoncc approved these changes
앞서 리뷰했던 논리적 오류는 모두 깔끔하게 잘 고쳐졌네요! 
코드도 리팩터링이 많이 된 것 같구요 ㅎㅎ 
이번 미션 수고많으셨어요 (_ _) 다음 블랙잭도 화이팅!!!

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Game.kt
> +    val tilesList = mutableListOf<Tiles>()
외부에서 `game.tilesList.add()...`하는 식으로 리스트 값을 변경할 경로가 열려있다는 생각이 들어요!

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/TodayWordPicker.kt
> +        val index = (duration % wordList.values.size).toInt()
오찌에게 받은 유용한 피드백을 공유할게요 ㅎㅎ 

```
Duration: LocalDateTime 사이의 간격을 초나 나노초 단위로 나타냄
Period: LocalDate 사이의 간격을 년/원/일 단위로 나타냄

이 경우에는 날짜만 관련있지 시간은 관련이 없으므로, Duration보다는 Period를 사용하는 것이 어떨까 싶어요!
```

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +        val answerLetters = ArrayList<Letter?>(correctAnswer.letters)
`Letter`가 `nullable`한 이유가 뭘까요?! 
지워봤는데 테스트는 잘 통과해서 물어봅니다

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/test/kotlin/domain/LetterTest.kt
> +            row("aa"),
어차피 `단어 목록에 있어야 한다`는 조건에 걸리겠지만, 지금은 숫자같은 걸 넣어도 `Letter`가 문제없이 생성되네요

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/test/kotlin/domain/TodayWordPickerTest.kt
> +        val testNow = LocalDateTime.of(2021, 6, 21, 0, 0)
이제 굳이 `clock.now`를 모킹하지 않아도 테스트가 가능하군요😄

2023-02-01 14:33 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +            }
```suggestion
            if (letters[i] == answerLetters[i]) GREEN else tile
```
이런 형태는 어떤가요! 저는 몇번 써보니 마음에 들더라고요

2023-02-05 06:21 UTC, devHudi commented on wordle/src/test/kotlin/domain/TodayWordPickerTest.kt
> +        val testNow = LocalDateTime.of(2021, 6, 21, 0, 0)
사실 최종 목적이 clock.now 모킹을 하는 것이었는데 시간의 압박으로 포기해버렸습니다 ㅎㅎ;

2023-02-05 06:21 UTC, devHudi commented on wordle/src/main/kotlin/domain/Word.kt
> +            }
저도 코틀린은 이렇게 간결하게 쓰는게 더 좋다는 생각이 요즘 많이 들어요 👍👍

2023-02-05 06:21 UTC, devHudi commented on wordle/src/main/kotlin/domain/TodayWordPicker.kt
> +        val index = (duration % wordList.values.size).toInt()
아 저런 차이가 있었군요!... Duration 을 사용하기엔 오버 엔지니어링 이었군요! 좋은 클래스 배워갑니다 👍👍

2023-02-05 06:22 UTC, devHudi commented on wordle/src/main/kotlin/domain/Game.kt
> +    val tilesList = mutableListOf<Tiles>()
오.. 이건 커스텀 게터를 통해서 값을 줄 때 복사본을 줘야겠네요!.. 코틀린은 이런 점을 더 조심해서 사용해야겠군요 ㄷㄷ 생각 못해봤던 부분이었습니다

2023-02-05 06:25 UTC, devHudi commented on wordle/src/test/kotlin/domain/LetterTest.kt
> +            row("aa"),
글자 검증 조건을 빡빡하게 두지 않았던게, 지금 한글 워들 처럼 배리에이션이 나올 수 있지 않을까 했었는데 사실 지금은 말씀하신 것 처럼 알파벳만으로 제한하는 것도 안전하겠네요 👍👍

2023-02-05 06:25 UTC, devHudi commented on wordle/src/main/kotlin/domain/Word.kt
> +        val answerLetters = ArrayList<Letter?>(correctAnswer.letters)
어.. 요거 실수인 것 같아용 ㅋㅋㅋㅋ 😅

2023-02-05 06:26 UTC, merged