[써머] 코틀린 워들 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #11
Opened 2023-01-24 16:20 UTC by hyewoncc

잘 부 탁 드 립 니 다 ^ _ _ _ ^

2023-01-25 15:15 UTC, Ohzzi requested changes
람다부터 엘비스 연산자까지 굉장히 다양한 방법을 잘 써주셨네요 :)
리뷰는 한번이면 섭섭하니까, 생각해 볼 거리들에 대해 리뷰 및 RC 남겼습니다. 확인해주세요!

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +class Alphabet(val value: Char) {
이 클래스를 data class로 만들지 않고 eq, hashcode 를 모두 따로 정의해준 이유가 있나요?? data class를 만드는 써머의 기준이 궁금합니다!

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +        }
!!로 인해 연산자 오버로딩의 이점을 제대로 살리지 못하고 있는 코드 같아요!
아예 다른 방식으로 key가 존재하는 경우에 작동하는 함수인 computeIfPresent를 활용하는 것은 어떨까요?

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +    private val pool: MutableMap<Alphabet, Int> = alphabets.groupingBy { it }.eachCount().toMutableMap()
전 약간 다른 방식으로 람다를 사용했었는데, 코틀린 컬렉션 api와 람다의 세계는 정말 신기하네요...

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +    fun compare(other: Word): List<Compared> {
아마 compare라는 로직이 들어가서 Word를 data class로 만들지 않은 것이겠죠?

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerPolicy.kt
> +        val duration = Duration.between(LocalDateTime.of(2021, 6, 19, 0, 0), LocalDateTime.now())
Duration: LocalDateTime 사이의 간격을 초나 나노초 단위로 나타냄
Period: LocalDate 사이의 간격을 년/원/일 단위로 나타냄

이 경우에는 날짜만 관련있지 시간은 관련이 없으므로, Duration보다는 Period를 사용하는 것이 어떨까 싶어요!

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +            }
이 부분을 메서드 분리해서 continue를 사용하지 않고 early return을 사용하는 것은 어떤가요?

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +            }
추가로, 직접 테스트코드로 돌려본 것은 아니지만 다음과 같은 경우에 오류가 발생할 것 같은데 어떻게 생각하나요?
정답: silly
입력한 단어: lilly

나와야 하는 타일: 회색 초록 초록 초록 초록
실제로 나올 타일(예상): 노랑 초록 초록 초록 초록

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +        return alphabets.map { it.value }.joinToString(separator = "")
```suggestion
        return word
```
👀

만약 word가 프로퍼티라면 훨씬 간결해지고 빨라지겠군요

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +class Word(word: String) {
주 생성자 파라미터를 프로퍼티로 만들지 않은 특별한 이유가 있을까요?

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    private fun requireNotEnded() {
내부에서 check만 호출하는데 네이밍의 통일을 가져가보는 것은 어떨까요?

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerPolicy.kt
> +class ByDateTimePolicy : AnswerPolicy {
AnswerPolicy 안에 중첩 클래스로도 선언이 가능합니다. 그냥... 그런게 있기도 하다구요 :)

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/Views.kt
> +}
혹시 이 경우에는 it에 대한 화살표 제거 못하나요??

2023-01-25 15:15 UTC, Ohzzi commented on wordle/src/main/kotlin/Application.kt
> +private fun play(wordle: Wordle): MutableList<List<Compared>> {
<>안의 <>는 지양하는 것이 좋다고 우테코 리뷰에서 봤던 기억이 나네요...! (optional)

2023-02-02 13:20 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +class Alphabet(val value: Char) {
1. 값은 영어 알파벳만 들어올 것
2. 해당 영어 알파벳은 대소문자에 관계없이 같은 알파벳이면 동일함 

이 두가지 로직이 있어서 data class로 선언하기엔 부적절하다고 생각했어요

2023-02-02 13:27 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +        }
오 이런 좋은 방법이 있었군요... 적용했습니다!

2023-02-02 13:28 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +    fun compare(other: Word): List<Compared> {
맞습니다~

2023-02-02 13:30 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/AnswerPolicy.kt
> +        val duration = Duration.between(LocalDateTime.of(2021, 6, 19, 0, 0), LocalDateTime.now())
반영했습니다, 유용한 정보 고마워요👍

2023-02-06 14:21 UTC, merged

2023-02-07 14:11 UTC, hyewoncc commented on wordle/src/main/kotlin/domain/Word.kt
> +class Word(word: String) {
값객체 래핑으로 로직을 부여하고 싶어서 사용하지 않았습니다!

2023-02-07 14:12 UTC, hyewoncc commented on wordle/src/main/kotlin/Views.kt
> +}
못하는 것 같네요??

2023-02-07 14:13 UTC, hyewoncc commented on wordle/src/main/kotlin/Application.kt
> +private fun play(wordle: Wordle): MutableList<List<Compared>> {
맞습니다... `Compared`의 일급컬렉션으로 감싸주는 게 나을 것 같은데, 일급컬렉션에 유의미한 로직이 들어갈 것 같지 않아 그냥 노출하게 되었어요 :(