[후디] 코틀린 블랙잭 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #15
Opened 2023-02-25 14:55 UTC by devHudi

너무 커스텀 게터 남용했나 싶기도 하네용
나만의 기준을 만들어가는 중

2023-02-26 06:01 UTC, Ohzzi requested changes
코틀린 활용적으로는 흠 잡을 데 없는 것 같네요 후디!
도메인 규칙에 대해서만 좀 더 체크하고 넘어가봅시다 :)

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        get() = players.all { it.state != ParticipantState.HIT }
힛 => 카드를 한 장 더 받음 != 게임 진행
게임을 진행할 턴이더라도 스탠드를 할 수 있고, 기타 규칙이 더 복잡해지면 인슈어런스 등 다른 동작을 할 수 있는데 toHit이 붙는건 좀 어색한 것 같습니다! 그냥 딜러까지 포함하여 플레이어 여러명에 대해 턴이 돌아가는 형태로 구성해 보는 것은 어떨까요?

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/participant/ParticipantState.kt
> +}
블랙잭 상태는 없나요? 👀

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
data class로 만들지 않은 이유가 있나요? 👀

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Deck.kt
> +    private val deck: LinkedList<Card>
MutableList.removeAt(index: Int)는 삭제하는 위치의 element를 반환합니다. 때문에 pop 대신 removeAt을 사용하면 굳이 LinkedList를 사용하지 않고 좀 더 추상적인 타입으로도 사용이 가능할 것 같은데 어떻게 생각하세요?

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Hand.kt
> +            }
에이스는 1, 11점이죠.
그런데 블랙잭은 21점을 넘으면 버스트기 때문에, 에이스가 2장 이상이어도 무조건 한 장만 11점으로 계산할 수가 있습니다. 즉, 반복문을 탈 필요가 없을 것 같아요. 모든 에이스를 우선 1점으로 계산하고, 에이스가 한 장이라도 있다면 + 10점을 해서 계산한 뒤에 21점 이하라면 해당 값을 return하는 방식을 사용하는 것은 어떨까요?

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Rank.kt
> +    ACE("A", 10), // 기본적으로 10점 취급, 버스트 시 1점 취급
에이스는 11점이에요!!!!

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Shape.kt
> +    val koreanName: String
코리안 네임 :) ㅋㅋㅋㅋ

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +        }
how about
```kotlin
(1..52).forEach { poppedCards.add(deck.pop()) }
```

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +    }
무작위를 테스트 할 수가 있나요? 100만번을 돌리더라도 100만 1번째에서 실패할 수 있는게 무작위 테스트인 것 같은데요.
게다가 지금 이 테스트는 순서가 랜덤하게 섞이는 것과도 상관이 없어보이는 것 같은데 혹시 어떤 테스트인건가요? 👀

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/game/GameResultTest.kt
> +    }
플레이어, 딜러가 모두 버스트일 때의 테스트는 없을까요?

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/participant/DealerTest.kt
> +    }
2+3+8 = 13점
딜러는 스탠드가 아니라 힛을 또 해야 하는데요?! 👀

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Shape.kt
> +    CLOVER("클로버"),
그런데 결국 이 koreanName은 뷰에 필요한 것 아닌가요? 굳이 enum이 가지고 있을 필요가 있나요? enum 자체로서는 아무 의미가 없는 것 같아요

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +    }
함수명 명사... 쵸큼 불편...

2023-02-26 06:01 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        }
딜러는 플레이어 한 턴이 전부 끝난 뒤에 히트, 스탠드를 결정하는 것 아닌가요? 그렇다면 한 턴을 진행한 뒤에도 hit 가능한 플레이어가 있을 수 있을텐데요 👀

2023-03-01 11:05 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/participant/ParticipantState.kt
> +}
요 부분은 참여자가 히트 할 수 있는지를 판단하기 위한 상태라서, 점수에 대한 블랙잭은 별도로 상태에 포함하진 않았습니다!

2023-03-01 11:15 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
data class 는 copy()를 통해 private constructor를 노출한다고 하더라구요. 이렇게 생성된 카드는 캐싱되지 않으므로 (from 메소드를 안타서) 부득이하게 equals&hashCode와 toString을 재정의했습니당

2023-03-01 11:18 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Hand.kt
> +            }
도메인 비 전문가가 짠 코드가 이래서 무섭습니다

2023-03-01 11:19 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Hand.kt
> +            }
에이스 무조건 한장만 가능하군요;; 제 맘대로 되는줄

2023-03-01 11:19 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Shape.kt
> +    val koreanName: String
ㅎㅎ

2023-03-01 11:19 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Rank.kt
> +    ACE("A", 10), // 기본적으로 10점 취급, 버스트 시 1점 취급
컥

2023-03-01 11:20 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/participant/DealerTest.kt
> +    }
딜러는 한번만 히트할수 있는줄 알았어요..

2023-03-01 11:21 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Shape.kt
> +    CLOVER("클로버"),
저도 똑같은 생각을 했는데요. 뷰 전용 shape name 을 따로 분리하는게, 되려 복잡도를 더 높히는 것 같아서 적절히 타협했습니다.

2023-03-01 11:21 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Shape.kt
> +    CLOVER("클로버"),
자주 바뀌는 정보도 아니고, 도메인이 가지고 있어도 큰 문제없는 정보라 생각했어요

2023-03-01 11:23 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +    }
호호.. 바꾼다면 뭐로 바꿀것 같아요?

2023-03-01 11:23 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        }
딜러는 한번만 히트 할 수 있는거로 착각했습니다 고칠게요 :블루_꾸벅:

2023-03-01 11:24 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        get() = players.all { it.state != ParticipantState.HIT }
그게 더 좋은 것 같네요! 딜러도 턴을 선택하는 대상에 포함시켜야겠군요

2023-03-01 11:32 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Deck.kt
> +    private val deck: LinkedList<Card>
오 요거 코틀린 컬렉션에서 제공하는거군요 좋네요!

2023-03-01 11:34 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +        }
굳이 ignored 를 안써도 되군요. 왜 for문 썼징 😅

2023-03-01 11:36 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +        }
it 자체를 생략하면 왜 람다에서 it 사용 안하냐 하고 워닝띄우네용

```kotlin
(1..52).forEach { _ ->
            poppedCards.add(deck.pop())
        }
```
언더스코어 써서 해결했어요

2023-03-01 11:40 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +    }
동일한 생각을 했는데, 아주 희박한 상황에서 실패하는 케이스를 굳이 신경쓸 필요는 없다 생각했어요. 10개 덱을 랜덤으로 섞은 다음에, 52장을 모두 뽑아 10개의 카드 리스트로 만듭니다. 이 리스트를 Set 으로 만들면, 순서가 동일한 List는 중복으로 간주되어 제거될텐데요. 이렇게 제거된 카드 리스트가 없는지 있는지를 개수로 검증합니다..... 만 말로 설명하니까 이거 되게 난해하네요;;

2023-03-01 11:43 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/game/GameResultTest.kt
> +    }
헉 그 케이스 자체를 고려 안했네요! 로직도 수정했습니다!

2023-03-01 15:18 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/participant/ParticipantState.kt
> +}
그렇다 하더라도 BLACKJACK도 STAND나 BUST처럼 HIT가 불가능한 상태로 추가해두는게 좋을 지도...? (optional)

2023-03-01 15:19 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
아하 생성자가 노출되지 않는 문제 때문이었군요! 이해 완료!

2023-03-01 15:20 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +    }
좀 난해한 테스트 같네요! 가독성이 좋지 못한 테스트 같아요 👀

2023-03-01 15:21 UTC, Ohzzi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +    }
processNextPlayerTurn...? 아니면 goToNextPlayerTurn?

2023-03-02 16:26 UTC, hyeonic reviewed
후디 코드 훔칠 겸 구경하고 갑니다~

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        }
블꾸

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
뭔가 코틀린에서 생성 시점에 이런 저런 로직 처리가 불편해서 팩토리 메서드를 자주 고려하게 되더라구요! 후디는 어떤 측면에서 도입하게 되었나요?

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/controller/GameController.kt
> +    // TODO: 에러 핸들링 및 재시도 로직 추가
미래의 후디에게 위임...

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/controller/GameController.kt
> +    private lateinit var blackjackGame: BlackjackGame
`lateinit` 키워드가 편하긴 한데 뭔가 이후의 나에게 짬때리는 느낌이라 불편하더라구요. 어찌되었든 찰나의 순간에 nullable한 상태를 만들기도 하구요! 그럼에도 고려하게 되는 이유가 있을까요??

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/domain/card/Hand.kt
> +        }
카드가 중복되는 경우가 있나요??

2023-03-02 16:26 UTC, hyeonic commented on blackjack/src/main/kotlin/blackjack/domain/participant/Participant.kt
> +    }
워우 when 사용이 야무지네요!

2023-03-02 17:43 UTC, Ohzzi commented on blackjack/src/test/kotlin/blackjack/domain/participant/DealerTest.kt
> +    }
아니 저 근데 이거 헷갈려요 딜러 한 번 만 히트하는게 맞나요? ㅋㅋㅋㅋㅋㅋ 블랙잭 한지 너무 오래되어서 ㅋㅋㅋㅋ

2023-03-05 13:07 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Hand.kt
> +        }
개발자가 실수할수도 있다 생각해서 넣었습니당 ㅎㅎ

2023-03-05 13:09 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/controller/GameController.kt
> +    private lateinit var blackjackGame: BlackjackGame
names가 없으면 BlackjackGame을 생성하지 못하는 상황이라 부득이하게 사용했습니다. lateinit을 사용하더라도 BlackjackGame 이 null 일 위험도 크게 없는 부분이라고 생각했어요.

2023-03-05 13:09 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/controller/GameController.kt
> +    // TODO: 에러 핸들링 및 재시도 로직 추가
이거 구현해놓고 주석을 안지움 ㅎㅋㅋㅋ

2023-03-05 13:10 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/card/Card.kt
> +    }
이 부분은 캐싱을 위해 도입했습니다 👍

2023-03-05 13:10 UTC, devHudi commented on blackjack/src/main/kotlin/blackjack/domain/game/BlackjackGame.kt
> +        get() = players.all { it.state != ParticipantState.HIT }
반영했습니당 +1 +1

2023-03-05 13:11 UTC, devHudi commented on blackjack/src/test/kotlin/blackjack/domain/card/DeckTest.kt
> +    }
이 부분은 테스트가 어렵단건 인정하고 아예 테스트 코드를 제거하는 방향으로 수정했어요

2023-03-11 07:26 UTC, merged