[오찌] 코틀린 로또 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #3
Opened 2023-01-10 05:08 UTC by Ohzzi

코틀린... 어려워...

2023-01-10 16:28 UTC, hyewoncc requested changes
의도치 않았는데 요체를 쓰게 됐네요 
멋진 코드 잘 보고 갑니다 👍

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/WinningResult.kt
> +            return WinningResult(result)
개수가 0인 Rank도 필요해서 이렇게 했을 것 같아서 참고하시라고 슬쩍... 

```kotlin
val result = purchasedLotteries.map { winningLotto.judgeRank(it) }
  .groupingBy { it }.eachCount()
```

이렇게 하면 `Map<Rank, Int>`를 좀 더 깔끔하게 얻을 수 있습니다  
물론 개수가 0개인 Rank는 어떻게 처리하냐 하면 거기까지는 못짰어요 ㅎ;

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/LottoApplication.kt
> +    }
함수 선언을 아래로 내려줬다면 더 이해가 쉬웠을 것 같네요

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/LottoMachine.kt
> +    }
코틀린매직 

```kotlin
fun issueAutomatically(count: Int): List<Lotto> = (1..count).map { issueRandomLotto() }
```

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/LottoApplication.kt
> +    return lotteries
여기도 이렇게 줄일 수 있을 것 같은데, map 안에서 try~catch가 반복되는 형태가 바람직한지 모르겠네요

```kotlin
return (1..count).map { issueManualLotto() }
```

`issueManualLotteries`가 항상 `List<Lotto>`를 반환함이 보장되니까 부작용이 없다고 봐도 될 것 같기도 하고...?

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/Lotto.kt
> +    fun countMatches(target: Lotto): Int = numbers.count { target.contains(it) }
👍

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/LottoMachine.kt
> +    private val lottoNumberPool = (1..45)
`(1..45)` 괄호를 떼면 컴파일이... 과연 될까요 안될까요?!

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/LottoNumber.kt
> +        private const val MAX_VALUE = 45
사견인데 `companion object`가 자바랑 달리 아래에 위치하는 게 주류다 보니 왠지 상수화 하면 영 읽기 불편하더라고요 
그래도 해야겠죠...? 
전.. 안했습니다.... 도무지 마음에 안들어서..

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/PurchaseMoney.kt
> +) {
클래스 내용물을 보면 도메인 규칙을 담고 있는데, 데이터 클래스를 사용하는 게 적절한가 의문이 드네요 
[코틀린 공식 문서](https://kotlinlang.org/docs/data-classes.html)를 보면 데이터 클래스는 값 보관에 중점이 맞춰져있는 것 같아서요

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/util/StringUtils.kt
> +fun String.isNumeric(): Boolean = chars().allMatch { Character.isDigit(it) }
`isNumeric()`보고 이런 기가멕힌게 있었는데 몰랐네; 했는데 확장함수였네요 ㅋㅋㅋㅋ 👍

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/view/Views.kt
> +    }
아래에서 `FAILED`를 걸러줬는데 여기에도 쓴 건 심신의 안정을 위해선가요?

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/main/kotlin/view/Views.kt
> +        ${"-".repeat(10)}
그냥 "----------" 쓰는 거랑 차이가 있나요?! 궁금합니다

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/test/kotlin/domain/LottoTest.kt
> +            shouldThrow<IllegalArgumentException> { Lotto.from(it) }
kotest의 `.forAll{ shouldThrow~ }`를 사용하면, 테스트 케이스가 일부 실패했을 때 좀 더 상세한 콘솔메시지를 볼 수 있어요 
<img width="798" alt="image" src="https://user-images.githubusercontent.com/80666066/211603973-5e4ec2d0-96c9-4822-b1c5-f201ea3d6c62.png">

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/test/kotlin/domain/PurchaseMoneyTest.kt
> +    }
테케 추가해보면 어떨까요?

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/test/kotlin/domain/WinningLottoTest.kt
> +        ).forEach { (lotto, rank) -> winningLotto.judgeRank(lotto) shouldBe rank }
오... kotest가 이런 방식도 지원하는군요 
이걸 몰라서 케이스 나눠서 했는데...

2023-01-10 16:28 UTC, hyewoncc commented on lotto/src/test/kotlin/domain/WinningResultTest.kt
> +    "당첨 로또와 구매한 로또로 결과를 판정할 수 있다." {
`WinningResult`가 `Map<Rank, Int>`를 감싼 일급컬렉션으로 보이는데, 거기에 따른 도메인 로직이 아니라 일급컬렉션을 만들기 위한 집계 로직만 있어서, 꼭 필요한 클래스인지 의문이 드네요
위에서는 긴가민가 했는데 테스트를 보니 집계만 테스트 하게 된 게 확연히 보여서요  
수익률 계산 로직 등 결과 연산과 관련된 로직이 한 곳에 모이면 더 좋을 것 같은데 어떻게 생각하시나요?

2023-01-11 02:03 UTC, injoon2019 commented on lotto/src/main/kotlin/domain/LottoMachine.kt
> +    }
홀리..

2023-01-11 06:00 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/LottoMachine.kt
> +    }
어 이거 당연히 되는건데 왜 안된다고 생각했지... ㅋㅋㅋㅋㅋㅋ

2023-01-11 06:03 UTC, Ohzzi commented on lotto/src/main/kotlin/LottoApplication.kt
> +    }
제가 이해한게 맞다면 55번 라인부터의 로직이 더 위로 오고, 중첩 함수 선언부가 로직의 아래로 내려가라는 이야기 같은데, 로직에서 중첩 함수를 사용하고 있기 때문에 중첩 함수를 먼저 선언해주어야 해서 안되는 것 같습니다 :)

2023-01-11 06:22 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/WinningResult.kt
> +            return WinningResult(result)
enum가지고 개수가 0개인 베이스 map을 만들고, 이렇게 람다로 만든 map을 putAll 하는걸로 바꿨습니다. null-safe 만들었네요 ㅎ

2023-01-11 06:26 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/LottoMachine.kt
> +    private val lottoNumberPool = (1..45)
되네요 👀

2023-01-11 06:37 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/LottoNumber.kt
> +        private const val MAX_VALUE = 45
근데 왜 아래에 위치하는 걸까요? inner class 비슷한 느낌이려나요?

2023-01-11 06:38 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/PurchaseMoney.kt
> +) {
수정해보도록 하겠습니다 :)

2023-01-11 07:42 UTC, Ohzzi commented on lotto/src/test/kotlin/domain/WinningResultTest.kt
> +    "당첨 로또와 구매한 로또로 결과를 판정할 수 있다." {
`로직을 한 곳에 모이면 좋겠다`라는 이유에서라면 말씀하신 부분이 타당해 보이네요. 이동시키도록 하겠습니다 :)

2023-01-11 07:45 UTC, Ohzzi commented on lotto/src/main/kotlin/view/Views.kt
> +        ${"-".repeat(10)}
좀 더 있어보이잖아요 ㅋ

2023-01-11 07:46 UTC, Ohzzi commented on lotto/src/main/kotlin/view/Views.kt
> +    }
컴파일이 안돼요.... ㅠㅠ

2023-01-11 07:52 UTC, Ohzzi commented on lotto/src/test/kotlin/domain/LottoTest.kt
> +            shouldThrow<IllegalArgumentException> { Lotto.from(it) }
forEach로 해도 실패한 라인이 나오긴 하니까 상관 없겠다고 생각했었는데, forAll이 좀 더 자세한 것 같아서 forAll로 교체했습니다 :)

2023-01-13 15:13 UTC, hyewoncc commented on lotto/src/main/kotlin/LottoApplication.kt
> +    }
오...? 그렇군요  제가 알못이었네요

2023-01-13 15:58 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/LottoNumber.kt
> +        private const val MAX_VALUE = 45
자바 <-> 코틀린 코드 변환 했을 때 이렇게 된다는 걸 보면 그런 느낌인 것 같네요

2023-01-13 15:59 UTC, hyewoncc commented on lotto/src/main/kotlin/view/Views.kt
> +    }
허걱...

2023-01-13 16:00 UTC, hyewoncc commented on lotto/src/main/kotlin/view/Views.kt
> +        ${"-".repeat(10)}
ㅋㅋㅋㅋㅋ더 길어졌는데도요?! 취존하겠습니다

2023-01-13 16:29 UTC, hyewoncc requested changes
리뷰는 두 번이 국룰이겠죠
마지막까지 화이팅

2023-01-13 16:29 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/Lotto.kt
> +        require(numbers.size == numbers.distinct().size) { "로또 번호에 중복이 있을 수 없습니다." }
지금보니 `LottoNumber`가 data class 라서 이렇게 해도 되네요
```java
require(numbers == numbers.distinct())
```

2023-01-13 16:29 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/LottoNumber.kt
> +        require(value in MIN_VALUE..MAX_VALUE) { "로또 번호는 1 이상 45 이하여야 합니다." }
이왕 상수로 선언한 거, 예외 메시지도 상수를 사용한다면 변경에 더 유연할 것 같네요
로또 규칙이 바뀔 확률은 적다고 생각하지만...
```java
require(value in MIN_VALUE..MAX_VALUE) { "로또 번호는 $MIN_VALUE 이상 $MAX_VALUE 이하여야 합니다." }
```

2023-01-13 16:29 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/PurchaseCount.kt
> +    operator fun minus(other: PurchaseCount) = PurchaseCount(value - other.value)
산술 연산자 오버로딩 👍

2023-01-13 16:29 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/PurchaseMoney.kt
> +    val value: Int
지난 리뷰 후로 일부는 삭제되고 일부는 추가되는 변경이 있었는데요, 
어떤 기준으로 수정했는지, data class의 사용 목적은 무엇인지 오찌의 의견이 궁금합니다

2023-01-15 10:11 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/LottoNumber.kt
> +        require(value in MIN_VALUE..MAX_VALUE) { "로또 번호는 1 이상 45 이하여야 합니다." }
오호 이건 생각 못했네요

2023-01-15 10:22 UTC, Ohzzi commented on lotto/src/main/kotlin/domain/PurchaseMoney.kt
> +    val value: Int
코틀린 인 액션 4장을 보면 데이터 클래스의 사용처에 대해
`어떤 클래스가 데이터를 저장하는 역할만을 수행한다면` 이라고 되어 있습니다.
기존 코드에서는 PurchaseMoney가 돈이라는 값 보관 외에도 돈에 해당하는 만큼의 로또 구매 가능 횟수 등을 계산하는 역할도 하고 있었습니다. 하지만 이 경우 값을 보관한다기 보다는 입력받은 값을 가지고 계산하는 클래스가 되어버리는 것 같더라고요. 그래서 Money와 Count를 분리했습니다. 계산하는 로직은 제외하고, Money와 Count 각각이 가져야 할 생성자의 도메인 규칙만 data class가 담도록 했습니다. VO를 만들때 사용하면 될 것 같아요.

2023-01-15 15:20 UTC, hyewoncc commented on lotto/src/main/kotlin/domain/PurchaseMoney.kt
> +    val value: Int
굿이에요 굿굿굿

2023-01-15 15:20 UTC, hyewoncc approved these changes
어푸 드리겠습니다💯
머지는 셀프라고 들었어요 
수고했습니다 오찌~

2023-01-15 16:17 UTC, merged