[오찌] 코틀린 워들 미션 제출합니다
woowacourse-study/2023-Kotlin-Basic pull request #7
Opened 2023-01-22 13:03 UTC by injoon2019

리뷰 잘 부탁드립니다. 워들 게임이 재밌네요!

2023-01-24 01:46 UTC, jayjaehunchoi approved these changes
심심...

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/Application.kt
> +    printGameResult(win = board.win(), answer = board.answer)
ktlintFormat ..
```suggestion
    printGameResult(
           win = board.win(), 
           answer = board.answer
     )
```

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/domain/Board.kt
> +    }
맨 아래로 ..

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/domain/Board.kt
> +        }
require...

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/domain/Wordle.kt
> +            for (i in (0..(tryAnswer.length() - 1)) step 1) {
```suggestion
           (0 until tryAnswer.length()).forEach { }
```

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/domain/Wordle.kt
> +                }
```suggestion
                when {
                    values[i] == tryAnswer[i] -> this.append(Color.G)
                    tryAnswer[i] in values ->  this.append(Color.Y)
                    else -> this.append(Color.W)
                  }
```

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/Application.kt
> +private fun playRound(board: Board) {
tailrec ..

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    }
data class ..?

2023-01-24 01:46 UTC, jayjaehunchoi commented on wordle/src/test/kotlin/domain/AnswerSelectorTest.kt
> +internal class AnswerSelectorTest : StringSpec({
funSpec 쓰기로 했구나 ..

2023-01-24 06:31 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Wordle.kt
> +                }
이건 선넘었다

2023-01-26 16:18 UTC, hyeonic requested changes
안녕하세요 토르, 매트입니다 😃

설에도 일하시면서 미션까지 진행하기 힘드셨을 텐데, 고생하셨습니다! 다양한 사람들의 코드를 보다보니깐 코틀린 사용에 미숙한 부분도 더 빠르게 습득할 수 있는 것 같아요! 새로운 키워드들도 많이 알 수 있어서 좋은 시간이었습니다. 다만 wordle 게임 요구사항과 상이한 부분이 있어서 이부분까지 보완되면 더욱 좋을 것 같아요! 시간 나실 때 리뷰 확인해주시면 감사하겠습니다. 고생하셨습니다!

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/AnswerSelector.kt
> +private val baseDate = LocalDate.of(2022, 6, 19)
전역 변수와 companion object는 단순한 취향 차이인가요? 혹은 컨벤션에 따라 사용하는 건가요?

전역 변수 이름에 대한 컨벤션도 궁금하네요 ㅎㅎ

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/AnswerSelector.kt
> +}
`findTodayAnswer()`를 함수로 활용했을 때와 싱글톤 객체의 메서드 활용했을 때 어떠한 차이가 있을지 쉽게 예측이 되지 않더라구요. 

실질적으로 `main()` 함수 내에서만 활용이 되고 있는데, `object`라는 키워드를 통해 객체 내에 속한 메서드로 활용한 이유가 있을까요?

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Board.kt
> +    }
보통 `companion object`는 맨 아래 두는게 국룰인가요?! 

이런식으로 정적 팩토리 메서드를 활용할 수 있네요! 배워갑니다 😃

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Board.kt
> +) {
오 안그래도 private 생성자로 막고 싶었는데, 이런식으로 활용할 수 있네요 👍

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Color.kt
> +}
요구사항의 경우에는 타일을 아래와 같이 표기하고 있습니다.

```
WORDLE을 6번 만에 맞춰 보세요.
시도의 결과는 타일의 색 변화로 나타납니다.
정답을 입력해 주세요.
hello

⬜⬜🟨🟩⬜

정답을 입력해 주세요.
label

⬜⬜🟨🟩⬜
🟨⬜⬜⬜🟩
```

맞춰서 출력되면 더욱 좋을 것 같네요 ㅎㅎ

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +        private val alphabets = ('a'..'z')
보통 const만 대문자로 표기하는 건가요?? 상수라는 용도 자체는 비슷한 것 같은데, 컨벤션이 궁금하네요!

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    fun length(): Int =
`Wordle` 내부에서만 사용하니 private로 접근자를 제한해도 좋을 것 같네요!

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +                }
ㅋㅋㅋㅋㅋㅋㅋㅋ

정답이 제대로 출력되지 않고 있는 것 같아요! 리뷰 일을 기준으로 정답이 `mount`인 상황에서 진행해보았습니다.
```bash
WORDLE을 6번 만에 맞춰 보세요.
시도의 결과는 타일의 색 변화로 나타납니다.
정답을 입력해 주세요.
marry
GWWWW
정답을 입력해 주세요.
mimic
GWYWW
GWYWW
정답을 입력해 주세요.
mount
GGGGG
GGGGG
GGGGG
승 : true
정답: mount
```

추정한 단어를 모으는 리스트 부분에 문제가 있는 것 같습니다! 확인 한번 해보면 좋을 것 같네요 😃

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    }
연산자 오버로딩 예전에 C++할 때나 써봤던 것 같은데 굉장히 신기하네요. 덕분에 일급 컬렉션 같은 것도 진짜 컬렉션 처럼 활용 가능할 것 같아요 👍

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    }
그러게요! data class로도 충분히 활용가능할 것 같은데, 의도가 궁금합니다!

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/view/GameView.kt
> +    return readln()
오 `String`을 return 하는 `readLine()`도 있었네요..

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/view/GameView.kt
> +    println(result.joinToString(separator = "\n"))
보통 `separator = "\n"`로 명시하거나 안하는 부분에 차이가 있을까요?

2023-01-26 16:18 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +                }
추가로 `mount`일 때 `mimic`으로 추정할 경우 `GWWWW`로 출력되야 합니다! [wordle 나무위키](https://namu.wiki/w/Wordle) 세부 규칙을 살펴보면 더욱 자세히 명시되어 있어서 확인해보면 좋을 것 같아요!

2023-01-29 02:13 UTC, injoon2019 commented on wordle/src/main/kotlin/Application.kt
> +    printGameResult(win = board.win(), answer = board.answer)
이거...자동정렬 먹이면 이렇게 된거..? 왜..나는..안되는거지..ktlintformat 적용하고 정리하니까 와일드카드 import만 풀리는데

2023-01-29 02:14 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Board.kt
> +    }
이건 회사에서 쓰는데로..

2023-01-29 02:15 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Board.kt
> +        }
이것도...커스텀..예외를..못던지니..그냥 통일감 있게 throw를 쓰게되네

2023-01-29 02:21 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    }
`It is not unusual to create classes whose main purpose is to hold data. In such classes, some standard functionality and some utility functions are often mechanically derivable from the data.` [코틀린 문서](https://kotlinlang.org/docs/data-classes.html)에 나와있는 Data class 설명인데요, 말 그대로 data를 저장하고 꺼내쓰기 위한 클래스에 쓰면 좋다고 생각했어요. 

eq/hc, toString이 필요하면 -> data class쓰자 (x)
data class를 쓰면 -> eq/hc, toString 재정의 해준다 (o)

이렇게 생각했네요. 혹시 다른 생각이시면 알려주세요!

2023-01-29 02:38 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
> +            for (i in (0..(tryAnswer.length() - 1)) step 1) {
오 감사합니다

2023-01-29 02:47 UTC, injoon2019 commented on wordle/src/main/kotlin/Application.kt
> +private fun playRound(board: Board) {
![image](https://user-images.githubusercontent.com/46641538/215301620-0017d227-a2c4-4049-b641-23732ed2f1c1.png)

꼬리 재귀가 아니라고 나와서.. 한번 생각해보겠음다

2023-01-29 02:47 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Board.kt
> +    }
코틀린 컨벤션은 젤 아래에 두는거에요!

2023-01-29 02:50 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    }
저도 실제 써본건 이번 미션하면서 처음인데 편하더라고요!!

2023-01-29 03:00 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
> +                }
![image](https://user-images.githubusercontent.com/46641538/215302095-4a2a1e30-e43f-43ec-9a2e-f37d68eeb51d.png)

이게 있었군요.. 다른 리뷰 반영하고 수정해보겠습니다!

2023-01-29 03:08 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerSelector.kt
> +private val baseDate = LocalDate.of(2022, 6, 19)
코틀린인액션 보면 자바의 static 변수들 그냥 파일 변수로 빼서 써라고 했던거 같은데 사실 회사에서는 100% companion object 안에 선언해서 쓰고 있기는해요. 그냥 시도를 한번 해봤습니다. 뭔가 전역 변수 느낌도 나고 import 바로 앞에 있으니 자바를 사용하던 입장에서 가독성이 좋은 것 같지도 않네요ㅎㅎ

2023-01-29 03:11 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerSelector.kt
> +}
`findTodayAnswer()`가 메인의 함수에 있어도 됐을 것 같다는 말씀이시죠?? 저는 관심사의 분리라고 생각했습니다. baseDate 가 변경되거나 오늘의 정답을 고르는 로직은 언제든지 바뀔 수 있으니 분리해서 객체를 생성하는게 좋다고 생각했습니다. 매트는 main에 있는게 더 나을것 같으신가요?

2023-01-29 03:13 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
> +        private val alphabets = ('a'..'z')
alphabets 변수는 정확히 말하면 상수는 아니지 않나요??

![image](https://user-images.githubusercontent.com/46641538/215302507-2c845524-617b-4c33-b2b1-bde2a5c19fa9.png)

실제로 const 키워드를 붙이면 오류가 나는데요,  const는 원시타입이나 String에만 붙일 수 있다고 합니다!

2023-01-29 03:39 UTC, injoon2019 commented on wordle/src/main/kotlin/view/GameView.kt
> +    println(result.joinToString(separator = "\n"))
정답을 입력해 주세요.
sound
WGGWG, WGGWG, WGGWG, WGGWG

없으면 이렇게 나옵니다!

2023-01-29 10:15 UTC, hyeonic commented on wordle/src/main/kotlin/domain/AnswerSelector.kt
> +}
아 단순히 파일 내부에 속한 함수를 말씀드린 겁니다!

아래는 `AnswerSelector.kt`라고 가정할게요.

```kotlin
package domain

import java.time.LocalDate

private val baseDate = LocalDate.of(2022, 6, 19)

fun findTodayAnswer(today: LocalDate, words: List<String>): String {
    val daysDifference = today.minusDays(baseDate.toEpochDay()).toEpochDay().toInt()
    return words[daysDifference % words.size]
}
```

객체에 속하지 않고 행위만 가진 fun만 둬도 괜찮지 않을까 생각해봤어요!

2023-01-29 10:18 UTC, hyeonic commented on wordle/src/main/kotlin/view/GameView.kt
> +    println(result.joinToString(separator = "\n"))
아 `separator =`이 부분을 말씀 드린 거예요! 생략해도 될 것 같은데, 코틀린이 알아서 다 추측해주니깐 보통은 컨벤션에 맞춰서 표기하는지 궁금하네요!

2023-02-03 10:13 UTC, hyeonic approved these changes
기간이 많이 지났으니 우선 approve 하겠슴다! 미션 고생하셨습니다 😃

2023-02-03 10:13 UTC, hyeonic commented on wordle/src/main/kotlin/Application.kt
> +private tailrec fun playRound(board: Board) {
👍

2023-02-03 10:13 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
> +    private fun length(): Int =
👍

2023-02-03 10:13 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Wordle.kt
>          }
with 키워드 이제 이해가 되네요 ㅋㅋ 코틀린 진짜 이것저것 지원하는게 엄청 많은 것 같아요!

2023-02-05 06:05 UTC, merged

2023-02-05 06:05 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Wordle.kt
>          }
그쵸 ㅎㅎ 이거 코틀린 인액션에도 이 부분 다루는게 있어서 보셔도 좋을거 같아요