[매트] 코틀린 워들 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #8
Opened 2023-01-23 07:52 UTC by hyeonic

코린이 워들 미션 제출합니다! 아직 자바 냄새가 짙게 배어 있어서 감안 해주시고 봐주십쇼 😃

2023-01-24 01:56 UTC, jayjaehunchoi approved these changes
심심해서 ..

2023-01-24 01:56 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/wordle/Application.kt
> +    val game = Game(wordsReader = FileWordsReader(), ioProcessor = ConsoleIOProcessor(Scanner(System.`in`)))
코틀린은 함수가 일급 객체이다 ....

2023-01-24 01:56 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    answerExtractor: AnswerExtractor = FixedAnswerExtractor(),
val.. var..

2023-01-24 01:56 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/wordle/domain/Judgement.kt
> +        for (index in 0 until answer.value.length) {
```suggestion
        (0 until answer.value.length).forEach {  }
```

2023-01-24 01:56 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/wordle/domain/Word.kt
> +        val REGEX = Regex("^[a-zA-Z]*$")
👍👍👍👍👍👍👍

2023-01-24 01:56 UTC, jayjaehunchoi commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +    private fun retryNextLine(scanner: Scanner): String = try {
tairec .. return try..

2023-01-24 07:05 UTC, Ohzzi reviewed
그냥 지나가다 심심해서 몇가지만 리뷰 남겼습니다...
근데 전체적으로 타입 명시를 잘 안하는 것 같더라고요. (특히 중괄호로 안묶고 식을 그대로 대입하는 경우에)
팀바팀이겠지만 반환 타입이나 프로퍼티 타입의 경우는 명시해주는게 가독성에 더 좋지 않을까 생각합니다!

2023-01-24 07:05 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +    private fun toDays() = Duration.between(LocalDateTime.now(), STANDARD_LOCAL_DATE_TIME).toDays()
https://www.daleseo.com/java8-duration-period/

Period 쓰는게 더 나을 것 같기도 합니다?

2023-01-24 07:05 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +        val STANDARD_LOCAL_DATE_TIME: LocalDateTime = LocalDateTime.of(2021, 6, 19, 0, 0)
시분초는 안쓸 것 같은데 LocalDateTime -> LocalDate는 어떨까요

2023-01-24 07:05 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    private var judgements = mutableListOf<Judgement>()
```suggestion
    private val answer: Word = answerExtractor.extract(wordsReader.read())

    private var judgements: MutableList<Judgement> = mutableListOf()
```

프로퍼티 타입 정도는 명시하는게 안헷갈릴듯??

2023-01-24 07:05 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +        println("시도의 결과는 타일의 색 변화로 나타납니다.")
삼중 따옴표에 대해 공부해봅시다

2023-01-24 07:05 UTC, Ohzzi commented on wordle/src/test/kotlin/wordle/domain/WordTest.kt
> +        assertEquals(actual.value, word)
AssertJ가 아니라니... 👀

2023-01-26 05:48 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    private var judgements = mutableListOf<Judgement>()
이게 IDEA에서 다 표기가 되니깐 지우게 되더라구요 ㅋㅋ 물론 팀 컨벤션을 따르겠지만 보통 프로퍼티 타입 정도는 명시하는 편인가요?

2023-01-26 05:51 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +        println("시도의 결과는 타일의 색 변화로 나타납니다.")
```kotlin
"""
키워드
감사합니다.
""".trimIndent()
```

2023-01-26 05:52 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +    private fun toDays() = Duration.between(LocalDateTime.now(), STANDARD_LOCAL_DATE_TIME).toDays()
그러네요! 초/나노초가 아닌 기간을 계산하는 거라 Period가 더 적절한 거 같아요 😃

2023-01-26 05:55 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +    private fun retryNextLine(scanner: Scanner): String = try {
오 `tailrec`이란 키워드가 있네요! 재귀로 직관적으로 작성이 가능하지만 더 적은 자원을 사용하는 루프로 알아서 컴파일하는 부분이 굉장히 신기하네요 😃

2023-01-26 06:00 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Judgement.kt
> +        for (index in 0 until answer.value.length) {
```kotlin
class Judgement(
    private val answer: Word,
    private val guess: Word,
) {
    ...
    private fun fillGreenTiles(tiles: MutableList<Tile>, countOfChars: MutableMap<Char, Int>) {
        (0 until answer.value.length).forEach { fillGreenTile(it, tiles, countOfChars) }
    }
    ...
}
```

2023-01-27 15:22 UTC, devHudi requested changes
매트 고생하셨습니다!! 출근준비 잘 하세용 ㅎㅎ

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    }
오 `tailrec` 신기하네요. 재귀 함수를 컴파일시 반복문으로 바꿔주는 기능인가요?

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +
ㅎㅎ 매직넘버

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Word.kt
> +        val REGEX = Regex("^[a-zA-Z]*$")
요즘 고민하고 있는게, 상수만을 위한 `companion object` 사용이 적절한가? 인데요, 팩토리 메소드 등을 사용할 때에는 companion object 사용이 적절해보이는데, 상수는 오히려 파일 최상단에 private으로 선언하는게 가독성 측면에서 더 좋아보일때가 있어요. 저도 그래서 이번에는 단순 상수를 위한 것은 파일 상단에 선언했어요. 물론 `클래스.상수` 형태로 외부에서 사용해야한다면 companion을 사용해야겠지만... 위 상수는 `Word` 클래스에서만 사용되는것으로 보여요. 매트의 의견 주시면 감사하겠습니다!~

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Words.kt
> +    }
```suggestion
    fun validateNonExist(word: Word) {
        require(value.contains(word)) { "[예외] 사전에 존재하지 않는 단어입니다. (입력: ${word})" }
    }
```
코틀린엔 템플릿 문자열도 추가되어 가독성도 해치지 않는데, 위와 같이 디버깅을 위한 입력 데이터를 함께 출력해주는건 어떨까요?

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Judgement.kt
> +
`Word` 클래스에 직접 선언하지 않고, 확장함수를 사용한 이유가 있을까요?

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/infra/FileWordsReader.kt
> +    }
원시값에 `const` 사용 좋군요

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +            """.trimIndent()
triple quotes + trimIndent() 👍👍

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +    }
이 부분은 가독성 때문에 변수로 따로 분리하는게 좋을 것 같아요.

2023-01-27 15:22 UTC, devHudi commented on wordle/src/test/kotlin/study/MapTest.kt
> +}
학습테스트 👍👍

2023-01-27 15:22 UTC, devHudi commented on wordle/src/test/kotlin/wordle/domain/JudgementTest.kt
> +    )
테스트 케이스가 풍부해서 좋군요 👍

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Tile.kt
> +    fun isGray() = this == GRAY
```suggestion
    val isGreen
        get() = this == GREEN

    val isGray
        get() = this == GRAY
```

요렇게 커스텀 게터를 사용하면 좀 더 코틀린스럽게 사용할 수 있어용

2023-01-27 15:22 UTC, devHudi commented on wordle/src/test/kotlin/wordle/domain/WordsReaderTest.kt
> +
어 이거 살짝 뇌정지 오는데, WordsReader가 인터페이스인데 어떻게 생성자를 갖죠?! 뭐지?

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    private var judgements: MutableList<Judgement> = mutableListOf(),
```suggestion
class Game(
    private wordsReader: WordsReader,
    private val ioProcessor: IOProcessor,
    private answerExtractor: AnswerExtractor = FixedAnswerExtractor(),
    private var judgements: MutableList<Judgement> = mutableListOf(),
```

이 두개 파라미터는 필드로 사용되지 않네요!

2023-01-27 15:22 UTC, devHudi commented on wordle/src/test/kotlin/wordle/domain/WordTest.kt
> +        assertEquals(actual.value, word)
Kotest가 아니라니... 👀

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/infra/FileWordsReader.kt
> +    }
오.. 전 `java.io.File` 썼는데, 코틀린에서 좋은게 있었네요! 배워갑니다!

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/infra/FileWordsReader.kt
> +
도메인이 파일 읽어와도 될까요? 라고 남기려고 했는데 인프라였네요 머쓱

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +        val index = abs(toDays() % words.size)
나머지 연산에 절댓값을 씌우는 특별한 이유가 있을까요? 아래와 같이 제거해도 테스트는 모두 통과하는 것으로 보여요.

```suggestion
        val index = toDays() % words.size
```

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    }
try ~ catch 를 식(expression)으로 사용하는 것도 좋네요

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +        .any { it.all(Tile::isGreen) }
마찬가지로 이런 것들도 메소드대신 커스텀 게터를 사용하면 좋을 것 같아요. 아무래도 코틀린은 getter, setter 대신 프로퍼티를 직접 접근하는 형태로 코드를 작성하다보니 통일하는게 좋아보일것이라는 이유입니다!

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +        .any { it.all(Tile::isGreen) }
`isPlaying()` 포함입니다! `judgeAll()` 은 그대로 두어도 괜찮을 것 같아요

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +
이렇게 사용된다면 Judgement에 대한 일급컬렉션을 만들고, 그곳에 책임을 할당하는게 좋아보이기도 하네요!

2023-01-27 15:22 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/IOProcessor.kt
> +}
IOProcessor 인터페이스는 도메인이고, 구현체는 View 인 구조가 재밌는 것 같은데요, 이유가 궁금합니다!

2023-01-28 05:26 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    private var judgements = mutableListOf<Judgement>()
저는 프로퍼티로는 명시하는 편

2023-01-28 05:27 UTC, Ohzzi commented on wordle/src/main/kotlin/wordle/domain/Word.kt
> +        val REGEX = Regex("^[a-zA-Z]*$")
이거 토스 내부에서도 의견이 나왔던 것 같은데, 저도 상수만을 위한 companion object에 반대합니다

2023-01-29 09:43 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Word.kt
> +        val REGEX = Regex("^[a-zA-Z]*$")
저도 두 분 의견에 동의합니다. 파일 상단에 private으로 선언하여 사용하는 것이 가독성 측면에서도 더 나은 것 같네요. 내부 메모리 구조에 대해서는 아직 공부 해보지 않아서 두 가지 방식이 정확히 어떠한 차이가 있는지는 아직 모르겠어요!

2023-01-29 09:44 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Words.kt
> +    }
출력 뿐만 아니라 다방면으로 활용할 수 있겠네요 👍

2023-01-29 09:45 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Judgement.kt
> +
`Word`를 사용하는 부분에서 유일하게 `Jugment`에서만 사용할 것이라 판단해서 확장 함수를 활용해보았습니다! 확장 함수 자체를 써보기 위한 의도도 있어요 ㅎㅎ

2023-01-29 09:45 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/view/ConsoleIOProcessor.kt
> +    }
넵 맞춰서 분리하겠습니다!

2023-01-29 09:45 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Tile.kt
> +    fun isGray() = this == GRAY
오 이런식으로 활용할 수도 있네요 👍

2023-01-29 09:50 UTC, hyeonic commented on wordle/src/test/kotlin/wordle/domain/WordsReaderTest.kt
> +
바로바로 함수형 인터페이스입니다! 코틀린에서 인터페이스 선언 시 fun 키워드를 사용하면 함수형 인터페이스로 활용할 수 있더라구요!

```kotlin
fun interface WordsReader {

    fun read(): List<Word>
}
```

2023-01-29 09:51 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    private var judgements: MutableList<Judgement> = mutableListOf(),
사용하지 않는 부분 제거하겠습니다!

2023-01-29 09:52 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +        val index = abs(toDays() % words.size)
어... 안되길래 절대값 연산을 했던 것 같은데, 확인해보고 불필요하면 제거하겠습니다.

2023-01-29 09:52 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +        .any { it.all(Tile::isGreen) }
좋은 기능들을 적극 활용해봐야 겠네요!

2023-01-29 09:53 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/IOProcessor.kt
> +}
그냥 오랜만에 콘솔 입출력을 진행하다보니 뷰에 대한 의존성을 끊는 방법을 이것저것 고민해본 것 같아요! 역시 의도는 도메인 내부에 입출력에 대한 의존성을 끊기 위함입니다!

2023-01-29 10:27 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/Application.kt
> +    val game = Game(wordsReader = FileWordsReader(), ioProcessor = ConsoleIOProcessor(Scanner(System.`in`)))
함수로 행위를 전달할 수 있다는 의미인가유

2023-01-29 10:28 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    answerExtractor: AnswerExtractor = FixedAnswerExtractor(),
프로퍼티로 안써서 생략하긴 했는데 아련하네요... ㅋㅋㅋㅋㅋ

2023-01-29 11:40 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/FixedAnswerExtractor.kt
> +        val STANDARD_LOCAL_DATE_TIME: LocalDateTime = LocalDateTime.of(2021, 6, 19, 0, 0)
Period로 수정했슴다!

```kotlin
class FixedAnswerExtractor : AnswerExtractor {

    override fun extract(words: List<Word>): Word {
        return words[toDays() % words.size]
    }

    private fun toDays() = Period.between(LocalDate.now(), STANDARD_LOCAL_DATE).days

    companion object {
        val STANDARD_LOCAL_DATE: LocalDate = LocalDate.of(2021, 6, 19)
    }
}

```

2023-01-29 11:42 UTC, hyeonic commented on wordle/src/main/kotlin/wordle/domain/Game.kt
> +    }
그렇다고 하네요!

[tail-recursive-functions](https://kotlinlang.org/docs/functions.html#tail-recursive-functions)

2023-01-29 14:41 UTC, devHudi commented on wordle/src/main/kotlin/wordle/domain/Judgement.kt
> +
일반적으로 확장 함수는 호환성을 위해 사용한다고 알고있는데요, Judgement에서만 사용된다 하더라도 Word에 직접 로직을 구현하는게 응집도 측면에서 더 좋아보인다고 생각해요.

2023-01-29 14:41 UTC, devHudi commented on wordle/src/test/kotlin/wordle/domain/WordsReaderTest.kt
> +
오 인터페이스 앞에 fun 키워드가 있었구나

2023-01-29 14:43 UTC, devHudi approved these changes
코드 재밌게 잘 읽고 갑니다~! 이만 Approve 하것습니다! 고생했어요! 출근준비 화이팅!

2023-02-02 07:23 UTC, Ohzzi commented on wordle/src/test/kotlin/wordle/domain/WordsReaderTest.kt
> +
fun interface에는 operator fun invoke를 함께 써보도록 합시다

https://velog.io/@ohzzi/Kotlin-operator-fun-invoke

2023-02-03 10:07 UTC, merged