[봄] 코틀린 워들 미션 제출합니다.
woowacourse-study/2023-Kotlin-Basic pull request #9
Opened 2023-01-24 10:18 UTC by JangBomi

안녕하세요 갓 태어난 코틀린입니다. 
아무것도 모르네요 ㅎ 돌아만가라! 이러면서 짠거라 많은 회초리 부탁드립니다 😫

2023-01-24 14:09 UTC, injoon2019 approved these changes
봄 첫 미션 고생 많으셨습니다~ 코틀린 쓰신지 얼마 안되셨는데 벌써 엄청 많이 배우셨네요. 
궁금한거 조금 남겨봤고 다른 리뷰어 분들이 또 리뷰 많이 남겨줄거에요!

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Answer.kt
> +            val dayDiffer: Int = Period.between(STANDARD_DATE, LocalDate.now()).days
여기서 Int는 일부러 명시한건가요? 의도한거면 굿! 

저는 회사에서 LocalDate를 쓸 일이 많은데 파라미터로 받지 않으면 테스트하기 힘들어서 항상 가능하면 상위 클래스에서 파라미터로 받으려고 하는 편이에요

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerCandidates.kt
> +        ?: throw FileNotFoundException("words.txt 파일이 존재하지 않습니다.")
크 👍

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerChecker.kt
> +            val index: Int = answerAndIsMarked.getMarkingIndex(alphabet) ?: continue
타입을 선언할때도 있고 안하실때도 있으시네요. 기준이 궁금합니다!

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerChecker.kt
> +        answerAndIsMarked.zip(word.withIndex()) { wordAndIsMarked, answerWord ->
zip 함수 👍

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +    operator fun get(index: Int): CharAndIsMarked {
👍

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/CharAndIsMarked.kt
> +}
뒤에 {} 가 없어도 될거 같아요!

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +    }
이것도 토론 주제중 하나던데 봄은 부정어로 메서드 만드는걸 찬성하시는 타입이시군요!

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +    }
동반객체는 젤 아래 가는게 코틀린 컨벤션이라고는 하지만 저희 회사는 그냥 자바 static 처럼 상단에 놓고 씁니다. 저도 그래요

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +        }
저는 처음에 프로퍼티 엄청 헷갈렸는데 벌써 잘 쓰시네요! 코틀린에서는 람다안에서 it로 많이 쓰더라고요~ 저는 개인적으로 명시하는 것도 좋아요

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +    }
이것도 취향의 영역일 수 있는데 만약 색깔이 더 늘어나면 메서드가 더 늘아나나요? 저는 markColorAt(color: Color, index:  Int) 이 방식을 선호하는데 취향의 영역일 것 같습니다!

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/Word.kt
> +        }
``` kotlin
require(value in ANSWER_CANDIDATES) { "단어 리스트에 존재하지 않는 단어입니다." }
``` 
요렇게도 가능한데 커스텀 익셉션을 못던져서 저는 안쓰긴합니다

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/WordleGame.kt
> +                 val gameResult: GameResult = GameResult()) {
디폴트값 잘 쓰시네요~

2023-01-24 14:09 UTC, injoon2019 commented on wordle/src/test/kotlin/StudyTest.kt
> +
학습테스트 👍

2023-01-25 11:53 UTC, Ohzzi requested changes
처음이신데 코틀린 잘쓰시네요 봄! 몇가지 리뷰를 남겨보았습니다 :)

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +    }
😄

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Word.kt
> +        return value.map { c -> CharAndIsMarked(c) }.toMutableList()
```suggestion
        return value.map { CharAndIsMarked(it) }.toMutableList()
```

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +            return tiles.all { tile -> tile == Tile.GREEN }
```suggestion
            return tiles.all { it == Tile.GREEN }
```

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +    }
저희 회사는 아래에 씁니다!

companion object의 의미를 생각해보면 아래에 쓰는게 더 맞다고 생각해요. 우리가 중첩 클래스나 내부 클래스를 클래스 맨 상단에 선언하지 않듯이요!

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
```suggestion
                .filter { !it.value.isMarked }
                .filter { it.value.char == alphabet }
                .map { it.index }
```
👀

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/WordleGame.kt
> +        }
```suggestion
    val isInProgress: Boolean
        get() = !isEnd
```
더 간단하게 쓸 수 있을 것 같아요. 그리고 이것도 프로퍼티인데 함수보다 위에 선언하는게 좋지 않을까요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/WordleGame.kt
> +        }
정적 팩터리 메서드가 열려있다면 생성자는 private으로!

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/view/View.kt
> +    }
```suggestion
    gameResult.forEach { printRoundResult(it) }
```
이렇게도 가능할 것 같은데요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/test/kotlin/domain/AnswerCheckerTest.kt
> +        assertEquals(roundResult, RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)))
코틀린에서도 assertJ 사용 가능하답니다!
또한 Junit을 사용해도 kotest 형식으로
```kotlin
roundResult shouldBe RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)
```
가능합니다

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/view/View.kt
> +    val word = readLine() ?: throw IllegalArgumentException("정답을 입력해주세요!")
readLine은 String?을 반환하지만 readln은 String을 반환하므로 readln으로 대체하면 엘비스 연산자가 필요 없습니다!

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/view/View.kt
> +}
`=`으로 쓰기에는 너무 긴 구문 같습니다. return try로 변경하는 것은 어떨까요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Answer.kt
> +class Answer(val value: String) {
```suggestion
class Answer(
    val value: String
) {
```

보통은 프로퍼티를 이렇게 쓰더라고요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerChecker.kt
> +            if (answerAndIsMarked.doesNotContain(alphabet)) continue
이 부분을 합쳐볼 수 있지 않을까요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/WordleGame.kt
> +}
확장함수 👍

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerCandidates.kt
> +}
외부에서는 호출 못하게 private으로 막는 것은 어떨까요?

2023-01-25 11:53 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Answer.kt
> +class Answer(val value: String) {
추가로 Answer가 지금은 단어 풀에서 뽑아오지만, 직접 입력하거나 할 수도 있을 것 같은데, 그럴 때를 대비해서 Word의 규칙을 공유하도록 Word를 프로퍼티로 가지는 것은 어떨까요?

2023-01-29 04:50 UTC, JangBomi commented on wordle/src/main/kotlin/domain/Answer.kt
> +            val dayDiffer: Int = Period.between(STANDARD_DATE, LocalDate.now()).days
날짜 차이의 타입은 int다가 명시적이었으면 좋겠어서 타입 명시해줬었어요..!

코틀린은 타입 추론이 가능하니, 어떤 경우 타입을 적는게 좋을지 아닐지가 좀 헷갈리던데, 토르는 혹시 타입 적는 기준이 있나요??!

2023-01-29 04:55 UTC, JangBomi commented on wordle/src/main/kotlin/domain/AnswerChecker.kt
> +            val index: Int = answerAndIsMarked.getMarkingIndex(alphabet) ?: continue
코드 짤 당시에는 기준 없었던 것 같아요 ㅠ 
생각해봤을 때, 코틀린의 장점 중 하나가 굳이 타입 명시를 해주지 않아도 된다, 타입 추론이 된다 인 것 같고,
타입을 적어주지 않으면 코드수가 늘어나지 않고 타입을 보지 않아도 되니 좀 더 로직에 집중할 수 있다. 정도의 이유로
 
'타입이 정말 명시적으로 보여져야하는 곳 아니면 타입을 적지 않는게 좋을 것 같다' 라는 결론에 이르렀는데
토르의 생각도 궁금해요 😉

2023-01-29 04:56 UTC, JangBomi commented on wordle/src/main/kotlin/domain/CharAndIsMarked.kt
> +}
크 대박 👍

2023-01-29 04:59 UTC, JangBomi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +    }
넵 `!` 가 가독성이 좋은 것 같지가 않아서, 차라리 함수 이름을 부정어로 만들면 이 함수가 쓰이는 곳에서 이 함수가 확실하게 포함하지 않는다가 드러나지 않을까? 라는 생각이 있어요

토르는 부정어로 메서드 만들기 찬성하시나요 ?!?

2023-01-29 05:02 UTC, JangBomi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +        }
아하 근데 이 프로퍼티 만들면서 궁금했던게 아래처럼 함수로 만들어주는거랑 프로퍼티로 만들어주는거랑 뭐가 좋을까였는데,

``` kotlin
    fun isAnswerF(): Boolean {
        return tiles.all {it == Tile.GREEN}
    }
```

'정답인가?' 정도는 프로퍼티로 만들어도 되겠다 싶어서 프로퍼티로 선언했었어요. 혹시 토르는 프로퍼티와 함수를 구분하는 기준이 있나용

2023-01-29 05:10 UTC, JangBomi commented on wordle/src/main/kotlin/domain/Word.kt
> +        }
오 새로운거 배웠네요 한 번 써봤습니당

2023-01-29 05:11 UTC, JangBomi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +            return tiles.all { tile -> tile == Tile.GREEN }
오찌는 it 생략 가능하니 람다 내에서 it로 사용할 수 있다면 it로 적어주자! 인가요?!?

2023-01-29 05:12 UTC, JangBomi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
하핫 👀

2023-01-29 05:12 UTC, JangBomi commented on wordle/src/main/kotlin/domain/WordleGame.kt
> +        }
오 대박 👍

2023-01-29 05:20 UTC, JangBomi commented on wordle/src/test/kotlin/domain/AnswerCheckerTest.kt
> +        assertEquals(roundResult, RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)))
오 다음 미션할때 코테스트 써봐야겠너요

2023-01-29 05:23 UTC, JangBomi commented on wordle/src/main/kotlin/view/View.kt
> +}
오찌는 함수를 `=`, `{ return }` 요거 두 개 사용하는 기준이 길이인건가요??
여기 작성하면서 저는 저게 하나의 식(expression)이니까 `=` 로 사용해도 괜찮을 것 같다고 생각했어서 궁금해요
(리뷰 반영은 했습니당ㅋㅋ)

2023-01-29 05:34 UTC, Ohzzi commented on wordle/src/main/kotlin/view/View.kt
> +}
사실 저희 팀에서는 `=`를 안쓴다는 슬픈 이야기...
개인적으로 할 때는 inline으로 나오는 경우에만 씁니다 길어지면 확실하게 return이 있는게 가독성이 좋을 때가 많아서요

2023-01-29 05:35 UTC, Ohzzi commented on wordle/src/test/kotlin/domain/AnswerCheckerTest.kt
> +        assertEquals(roundResult, RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)))
근데 난 JUnit 쓸거임 ㅅㄱ

2023-01-29 05:36 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
분명 옆에서 알려준 것 같았는데... 👀

2023-01-29 05:36 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
그리고 filter 두 개 합치는게 성능상으로 더 좋아보입니다. 저러면 반복을 두 번 돌게 되네요.

2023-01-29 05:37 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +            return tiles.all { tile -> tile == Tile.GREEN }
네. 최대한 짧게 쓰자는 주의입니다.

2023-01-29 05:39 UTC, Ohzzi commented on wordle/src/main/kotlin/domain/Answer.kt
> +            val dayDiffer: Int = Period.between(STANDARD_DATE, LocalDate.now()).days
토르는 아니지만 개인 취향
- 프로퍼티는 무조건 타입을 적는다.
- 로컬 변수는 IDE 기능을 빌리고 웬만하면 안적는다.
  - 진짜 누가 봐도 헷갈리겠다 싶으면 적음.

2023-01-29 05:45 UTC, JangBomi commented
@injoon2019 @Ohzzi 리뷰 반영 했습니다!!! 질문 몇개 남겨봤어요 😉

2023-01-29 10:21 UTC, hyeonic commented on wordle/src/main/kotlin/domain/Answer.kt
> +            val dayDiffer: Int = Period.between(STANDARD_DATE, LocalDate.now()).days
개취 or 회사 컨벤션?

2023-01-29 10:21 UTC, hyeonic commented on wordle/src/main/kotlin/domain/AnswerCandidates.kt
> +        ?: throw FileNotFoundException("words.txt 파일이 존재하지 않습니다.")
진짜 너무 깔끔하네요! 파일 이름만 알면 다 대응이 가능할 것 같네요 ㅎㅎ

2023-01-29 10:25 UTC, hyeonic commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
Java의 향기가...

2023-01-29 10:25 UTC, hyeonic commented on wordle/src/test/kotlin/domain/AnswerCheckerTest.kt
> +        assertEquals(roundResult, RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)))
뭐지?

2023-01-29 10:26 UTC, hyeonic commented on wordle/src/main/kotlin/view/View.kt
> +}
다 `{ return }`으로 통일 할래요~

2023-01-29 14:43 UTC, JangBomi commented on wordle/src/test/kotlin/domain/AnswerCheckerTest.kt
> +        assertEquals(roundResult, RoundResult(mutableListOf(GREEN, GREY, GREY, GREEN, GREEN)))
아놔

2023-01-29 14:44 UTC, JangBomi commented on wordle/src/main/kotlin/view/View.kt
> +}
오호 👍

2023-01-29 14:46 UTC, JangBomi commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +                .map { it -> it.index }
ㅋㅋㅋㅋ 반영 완료!

2023-01-30 13:38 UTC, Ohzzi approved these changes
굿! 다음 미션으로 넘어갑시다

2023-02-01 13:57 UTC, JangBomi commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +        }
자문자답이긴한데(ㅋㅋ) 이펙티브 코틀린 읽어보다가 관련 내용 있어서 발췌해서 공유합니다.

## 아이템 16, 프로퍼티는 동작이 아니라 상태를 나타내야한다. (p,95)

원칙적으로 프로퍼티는 상태를 나타내거나 설정하기 위한 목적으로만 사용하는 것이 좋고, 다른 로직 등을 포함하지 않아야 합니다.
어떤 것을 프로퍼티로 해야하는지 판단할 수 있는 간단한 질문이 있습니다. `이 프로퍼티를 함수로 정의할 경우, 접두사로 get 또는 set을 붙일 것인가?` 만약 아니라면, 이를 프로퍼티로 만드는 것은 좋지 않습니다.

좀 더 구체적으로 프로퍼티 대신 함수를 사용하는 것이 좋은 경우
- 연산 비용이 높거나, 복잡도가 O(1) 보다 큰 경우
- 비즈니스 로직(애플리케이션의 동작)을 포함하는 경우
- 결정적이지 않은 경우(같은 동작을 연속적으로 두 번 했는데 다른 값이 나올 수 있다면, 함수를 사용하는 것이 좋습니다)
- 변환의 경우(e.g. Int.toDouble())
- 게터에서 프로퍼티의 상태 변경이 일어나야 하는 경우

2023-02-05 06:07 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerChecker.kt
> +            val index: Int = answerAndIsMarked.getMarkingIndex(alphabet) ?: continue
저도 위의 오찌 생각과 비슷합니다 ㅎㅎ ide 도움을 받을 수 있는거는 도움을 받자는 생각이어서 ㅎㅎ 크게 보자면 변수 선언에는 안적고 메서드 파라미터나 리턴은 저는 적고 있어요

2023-02-05 06:09 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/AnswerMarkings.kt
> +    }
저는 안쓰려고 하는 편이에요! 근데 또 회사에서 제 메이트는 쓰시는걸 좋아하시더라고요? 하나를 확실히 정하기만 하면 뭐든 상관없을거 같아요. 저는 어디서 본건데 not~으로 시작하는 메서드를 만들면 그자체로 부정어인 동사로 메서드를 만들때 헷갈릴 수도 있다고 하더라고요 (ex. inclue <-> exclude) 이런것들.

2023-02-05 06:10 UTC, injoon2019 commented on wordle/src/main/kotlin/domain/RoundResult.kt
> +        }
저도 이걸 차리한테 들었고, 차리는 제이슨한테 들었는데 제이슨의 기준은 시간 복잡도 `O(1)`이냐 아니냐라고 하셨대요 ㅎㅎ 제이슨은 이펙티브 코틀린을 참고하셨을 수도 있겠네요!

2023-02-05 06:11 UTC, injoon2019 commented
봄 제가 주중에 바빠서 리뷰가 늦었네요 ㅎㅎ 고생많으셨습니다! 봄은 벌써 이펙티브 코틀린까지 보시는 것 같네요! 다음 미션에서 봐요!

2023-02-06 13:40 UTC, merged